import java.util.Scanner;

class Alpha{
	
	public void calc() throws ArithmeticException {
		
		System.out.println("Alpha Connection Established");
	
		Scanner scan = new Scanner(System.in);
			
		System.out.println("kindly enter the numerator for division");
			
		int n = scan.nextInt();
			
		System.out.println("kindly enter the denominator for division");
			
		int d = scan.nextInt();
			
		int res = n/d;
			
		System.out.println("result is: " + res);
			
		System.out.println("error occured");
			
		System.out.println("Alpha Connection Terminated");
	}
}


public class ExceptH_04 {

	public static void main(String[] args) {
		
		System.out.println("main connection established");
		
		Alpha1 a1 = new Alpha1();
		a1.calc();
		
		System.out.println("main connection terminated");

	}

}
